/* This file is generated by the flag editor util. Changes will be lost! */

export type Features = {
  AN_EXTRA_EXAMPLE: boolean;
  EXAMPLE_FLAG: boolean;
  OTHER_EXAMPLE_FLAG: boolean;
  THE_BEST_FLAG: boolean;
};
