// flagStorage.ts
import path from 'path';

import fsx from 'fs-extra';

import { Environments, FlagsState } from './types';

const CONFIG_DIRECTORY = 'features';
const FLAGS_FILENAME = 'flags.json';
const FEATURES_TYPEDEF_FILENAME = 'features.d.ts';
const ENVIRONMENTS_FILENAME = 'environments.json';
const ENABLE_DEBUG_LOGGING = process.env.LIT_FLAG_DEBUG === 'true' || false;

/** Logs debug information if debugging is enabled */
export function log(...args: any[]): void {
  if (ENABLE_DEBUG_LOGGING) {
    console.log(...args);
  }
}

/** Resolves the configuration path by walking up directories until a flags.json file is found. */
export async function resolveConfigPath(): Promise<string> {
  const { base, dir, root } = path.parse(process.cwd());
  let fileFound = false;
  let currPath = path.join(dir, base);

  while (!fileFound && currPath && currPath !== root) {
    // eslint-disable-next-line no-await-in-loop
    fileFound = await fsx.exists(path.join(currPath, CONFIG_DIRECTORY, FLAGS_FILENAME));

    if (!fileFound) {
      currPath = currPath.split(path.sep).slice(0, -1).join(path.sep);
    }
  }

  if (!fileFound) {
    throw new Error(
      `Could not find a ${FLAGS_FILENAME} in CWD or any parent dir. See README.md for more info.`
    );
  }

  return path.join(currPath, CONFIG_DIRECTORY);
}

/** Gets the file paths for flags and environments based on the config path */
export function getFilePaths(configPath: string): {
  environmentsFilepath: string;
  flagsFilepath: string;
  typeDefPath: string;
} {
  const environmentsFilepath = path.join(configPath, ENVIRONMENTS_FILENAME);
  const flagsFilepath = path.join(configPath, FLAGS_FILENAME);
  const typeDefPath = flagsFilepath.replace(FLAGS_FILENAME, FEATURES_TYPEDEF_FILENAME);

  return {
    environmentsFilepath,
    flagsFilepath,
    typeDefPath,
  };
}

/** Loads environments configuration from the given file path. */
export async function loadEnvironments(environmentsFilepath: string): Promise<Environments> {
  try {
    return await fsx.readJson(environmentsFilepath);
  } catch (e) {
    console.log(e);
    throw new Error(`Failed to load JSON from ${environmentsFilepath}. Probably not valid JSON!`);
  }
}

/** Loads flags state from the given file path. */
export async function loadFlags(flagsFilepath: string): Promise<FlagsState> {
  try {
    return await fsx.readJson(flagsFilepath);
  } catch (e) {
    console.log(e);
    throw new Error(`Failed to load JSON from ${flagsFilepath}. Probably not valid JSON!`);
  }
}

/** Saves environments to the given file path */
export async function saveEnvironments(
  environmentsFilepath: string,
  environments: Environments
): Promise<void> {
  log('writing file', { filepath: environmentsFilepath, state: environments });
  return fsx.writeJson(environmentsFilepath, environments, { spaces: 2 });
}

/** Saves flags state to the given file path */
export async function saveFlags(flagsFilepath: string, flagsState: FlagsState): Promise<void> {
  log('writing file', { filepath: flagsFilepath, state: flagsState });

  const flagOutput = Object.keys(flagsState)
    .sort()
    .reduce<FlagsState>((output, flagName) => {
      output[flagName] = flagsState[flagName]; // eslint-disable-line no-param-reassign
      return output;
    }, {});

  return fsx.writeJson(flagsFilepath, flagOutput, { spaces: 2 });
}

/** Writes type definitions for the flags */
export async function writeTypeDefinitions(
  typeDefPath: string,
  flagsState: FlagsState
): Promise<void> {
  const alphabetizedTypeDefs = Object.keys(flagsState)
    .sort()
    .map((flag) => `${flag}: boolean;`)
    .join('\n\t');

  const fileContent = `
/* This file is generated by the flag editor util. Changes will be lost! */
  
export type Features = {
\t${alphabetizedTypeDefs}
};
`;

  log('writing typedef file', { filepath: typeDefPath, state: flagsState });
  return fsx.writeFile(typeDefPath, fileContent);
}
